#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
F4 - Multi-channel eBPF rootkit detector (Rust-style, SPiCa-class).

A pure-Python simulation of the multi-channel rootkit-detection concept:
a rootkit hides by tampering with one observable of the kernel, so we
observe kernel state through several INDEPENDENT channels and flag a
rootkit when the channels disagree or a heartbeat vanishes.

Presented channels (simulated):

  A) eBPF-Tracepoint Sensors  - per-process syscall activity stream
     (in production: eBPF programs attached to tracepoints/kprobes)
  B) /proc Cross-View Reconciler - parse a fake /proc scenery that a
     rootkit has edited (processes/pid lists under /proc)
  C) Hardware-Timer Heartbeat - a periodic pulse generated by a kernel
     timer that a stealthy rootkit fails to suppress entirely

Detection: a rootkit is suspected if (1) the /proc view and the syscall
stream disagree about which processes exist/died, or (2) heartbeat pulses
vanish for too long. Suppression cases show that when an adversary kills
one channel, the remaining channels still converge on the verdict.

The production Rust + eBPF implementation is an integration point: this
simulation models the exact signal flows a low-level detector would fuse.
"""

import random
import sys


# --------------------------------------------------------------------------
# Simulated kernel observers
# --------------------------------------------------------------------------

class SyscallSensor(object):
    """Channel A - eBPF-style tracepoint stream of per-process syscalls.

    Each sample: {pid, ppid, name, alive, syscalls:[...], hidden}
    A rootkit may *hide* the syscalls of a descendant process (LD_PRELOAD
    /libc-shadowing style) but cannot delete the thread on the tracepoint
    stream entirely (that would require re-attaching hooks).
    """

    def __init__(self, events):
        self.events = events
        self.seen_pids = set()

    def stream(self):
        for ev in self.events:
            syscalls = list(ev["syscalls"])
            if ev.get("hidden"):
                syscalls = []  # rootkit intercepts tracepoint delivery
            yield {"pid": ev["pid"], "name": ev["name"],
                   "syscalls": syscalls, "alive": ev["alive"]}


class ProcView(object):
    """Channel B - simulated /proc cross-view.

    The rootkit edits /proc (removes the pid dir) so this view is
    incomplete: processes it hides are simply absent. Independent of A."""

    def __init__(self, procs):
        self.procs = procs  # dict pid -> name (post-edit view)

    def list(self):
        return dict(self.procs)


class TimerHeartbeat(object):
    """Channel C - hardware-timer pulse generator.

    The kernel timer fires N pulses per epoch. A well-implemented
    rootkit masks all pulses; a partially suppressive one masks some."""

    def __init__(self, base_pulse=10, seed=5):
        self.base_pulse = base_pulse
        self.rng = random.Random(seed)

    def pulses(self, epochs, kill_after=None):
        for ep in range(epochs):
            if kill_after is not None and ep >= kill_after:
                yield 0
                continue
            n = max(1, self.base_pulse - self.rng.randrange(0, 2))
            yield n


# --------------------------------------------------------------------------
# Rootkit simulation
# --------------------------------------------------------------------------

class Rootkit(object):
    """Model of a hidden process + its hiding strategy."""

    def __init__(self, pid, name="tk", ppid=2, seed=11):
        self.pid = pid
        self.name = name
        self.ppid = ppid
        self.rng = random.Random(seed)

    # Behaviors ---------------------------------------------------------
    def hide_from_proc(self):
        return True

    def intercept_syscalls(self, suppress):
        """Return whether the syscall stream is suppressed this epoch."""
        return suppress

    def mask_heartbeat(self, suppress):
        return suppress


# --------------------------------------------------------------------------
# Fusing detector
# --------------------------------------------------------------------------

class MultiChannelDetector(object):
    """Fuses channels A/B/C and produces per-epoch verdicts."""

    def __init__(self, window=3):
        self.window = window
        self.last_heartbeat_ok = False

    def fuse_epoch(self, syscalls, proc, pulses):
        """syscalls: list of pid names seen in A this epoch
           proc    : dict pid->name from B
           pulses  : list of timer pulse counts from C
        Returns (verdicts, evidence)."""
        verdicts = []
        evidence = []
        # A vs B
        b_pids = set(proc.keys())
        a_pids = set(syscalls.keys())
        syscalls_see = a_pids - b_pids     # in A (syscalls) but not in B (/proc)
        proc_only = b_pids - a_pids        # in B (/proc) but silent in A
        if syscalls_see:
            verdicts.append("A/B-CROSS-A (syscalls see pid, /proc does not)")
            evidence.append("active-in-A-absent-from-B:%s" %
                            sorted(syscalls_see))
        if proc_only:
            verdicts.append("A/B-CROSS-B (/proc lists pid, syscalls silent)")
            evidence.append("in-B-silent-in-A:%s" % sorted(proc_only))
        if not syscalls_see and not proc_only:
            verdicts.append("A/B-AGREE")
        # C heartbeat health
        hp = sum(pulses)
        if hp == 0:
            verdicts.append("HEARTBEAT-VANISHED")
            evidence.append("zero-pulses-in-epoch")
        elif hp < self.window:
            verdicts.append("HEARTBEAT-WEAK")
            evidence.append("pulses-%d-below-window" % hp)
        else:
            verdicts.append("HEARTBEAT-OK")
        # fusing: a rootkit is SIGNALLED when any channel raises alarm
        alarms = [v for v in verdicts
                  if v != "A/B-AGREE" and v != "HEARTBEAT-OK"]
        verdicts.append("VERDICT:" + ("SUSPECT" if alarms else "CLEAN"))
        return verdicts, evidence


# --------------------------------------------------------------------------
# Production integration point (Rust + eBPF)
# --------------------------------------------------------------------------

PRODUCTION_MAPPING = {
    "channel_A": {
        "simulated": "SyscallSensor per-process syscall activity stream",
        "rust_ebpf": "eBPF programs on tracepoint:sys_enter_* / "
                     "kprobe:sys_* feeding a shared ring buffer consumed "
                     "by a tokio task; pid/comm lookup via bpf_get_current_pid_tgid",
    },
    "channel_B": {
        "simulated": "ProcView parses a (possibly rootkit-edited) /proc map",
        "rust_ebpf": "Rust process-table reader (procfs) reconciled in "
                     "userland against kernel task_iter bpf_iter snapshots",
    },
    "channel_C": {
        "simulated": "TimerHeartbeat periodic pulse the rootkit fails to mask",
        "rust_ebpf": "a per-CPU hrtimer-driven eBPF kprobe (or skb timer) "
                     "emitting pulses; parked in a memory region the rootkit "
                     "cannot reach via userland",
    },
    "fuser": {
        "simulated": "MultiChannelDetector.fuse_epoch cross-agreement logic",
        "rust_ebpf": "Rust aggregator consuming the ring buffer(s), "
                     "computing disagreement sets and heartbeat-gap windows",
    },
}


def production_integration_note():
    """Return the Rust/eBPF integration-point documentation block."""
    L = "=" * 70
    out = [L,
           "  PRODUCTION INTEGRATION POINT (Rust-style / eBPF / SPiCa-class)",
           L]
    for chan, mapping in PRODUCTION_MAPPING.items():
        out.append("  %-10s | simulated : %s" % (chan, mapping["simulated"]))
        out.append("  %-10s | rust/ebpf: %s" % (" ", mapping["rust_ebpf"]))
    out.append(L)
    out.append("  The classes above are a 1:1 signal-flow model of a real")
    out.append("  multi-channel detector. Swap SyscallSensor/ProcView/")
    out.append("  TimerHeartbeat for the Rust + eBPF probes and keep the")
    out.append("  fuse_epoch decision logic as the aggregation core.")
    out.append(L)
    return "\n".join(out)


# --------------------------------------------------------------------------
# Scenario builder
# --------------------------------------------------------------------------

def build_scenario(seed, hide_proc=False, mute_sys=False, kill_hb=False):
    """Construct (procs, events) for one scenario.

    hide_proc : rootkit removes its pid dir from /proc (edits B)
    mute_sys  : rootkit intercepts its own syscall tracepoint stream (A)
    kill_hb   : rootkit masks the hardware-timer heartbeat outright (C)
    If none of the three is set, the rootkit is entirely absent -> clean
    baseline (nothing to hide)."""
    rng = random.Random(seed)
    has_rk = hide_proc or mute_sys or kill_hb
    rk = Rootkit(pid=9000 + seed % 50, seed=seed)
    procs = {}
    events = []
    for p in range(50, 54):
        nm = "srv-%d" % p
        procs[p] = nm
        events.append({"pid": p, "name": nm, "alive": True,
                       "syscalls": ["open", "read", "write", "close",
                                    "fcntl"] * 2,
                       "hidden": False})
    if not has_rk:
        return procs, events, None, False, False
    procs[rk.pid] = rk.name
    if hide_proc:
        del procs[rk.pid]
    events.append({"pid": rk.pid, "name": rk.name, "alive": True,
                   "syscalls": ["open", "read", "getpid", "ioctl"] * 3,
                   "hidden": mute_sys})
    return procs, events, rk, mute_sys, kill_hb


# --------------------------------------------------------------------------
# Detection matrix
# --------------------------------------------------------------------------

def run_matrix():
    """Run the core scenarios and assemble the detection matrix.

    Each row models an adversary action against the channels; the detector
    fuses all three and must still raise a SUSPECT verdict whenever at
    least one independent channel survives."""
    L = "=" * 70
    out = [L,
           "  F4 - MULTI-CHANNEL ROOTKIT DETECTOR (SPiCa-class)",
           L,
           "  Channels : A=syscall tracepoint stream, B=/proc cross-view,",
           "             C=kernel timer heartbeat",
           ""]
    cases = [
        ("baseline (no rootkit)",         False, False, 0),
        ("rk edits /proc (hide pid)",     True,  False, 0),
        ("rk kills channel A (tracepoints)", False, True, 0),
        ("rk kills channel B (/proc view)", True,  False, 0),
        ("rk kills channel C (heartbeat)", False, False, 1),
        ("rk suppresses A+B, C fails",    True,  True,  2),
    ]
    out.append("%-32s | %s" % ("Scenario", "Fused channel verdicts"))
    out.append("-" * 70)
    for label, hide_p, mute_a, hb_mode in cases:
        procs, events, rk, mute_sys, _ = \
            build_scenario(17, hide_proc=hide_p, mute_sys=mute_a)
        a = SyscallSensor(events)
        b = ProcView(procs)
        c = TimerHeartbeat(seed=3, base_pulse=6)
        det = MultiChannelDetector()
        syscall_map = {}
        for sample in a.stream():
            syscall_map[sample["pid"]] = sample["syscalls"]
        if mute_a:                   # adversarial channel-A kill: empty stream
            syscall_map = {}
        proc_map = b.list()
        pulses = list(c.pulses(epochs=1))
        if hb_mode == 1:             # adversarial channel-C kill: no pulses
            pulses = [0]
        elif hb_mode == 2:           # partial suppression: heartbeat stalls
            pulses = [1]
        verdicts, ev = det.fuse_epoch(syscall_map, proc_map, pulses)
        out.append("%-32s | %s" % (label, "; ".join(verdicts)))
        out.append("%-32s |   evidence: %s" % (" ", "; ".join(ev) or "-"))
    out.append("-" * 70)
    out.append("  READING: as long as ANY channel is independent of the")
    out.append("  attacker's reach, the fused verdict stays SUSPECT. The")
    out.append("  'rk kills channel A' row shows B/C catching the kill; the")
    out.append("  'A+B suppressed' row shows C (kernel timer) still fires --")
    out.append("  the classic SPiCa-class survival property.")
    out.append(L)
    return "\n".join(out)


# --------------------------------------------------------------------------
# Per-channel robustness (suppression cases)
# --------------------------------------------------------------------------

def channel_suppression_report():
    """Show that when an adversary kills ONE channel, the others still catch
    the rootkit (the multi-channel survival property)."""
    L = "=" * 70
    out = [L,
           "  CHANNEL-SUPPRESSION CASES (attacker disables a channel)",
           "-" * 70]
    # scenario: rootkit hides pid -> kill only ONE channel -> fuse the rest
    base_procs, base_events, rk, _, _ = build_scenario(4, hide_proc=True)
    rk_pid = rk.pid
    for dead in ("A", "B", "C"):
        if dead == "A":
            # A (tracepoints) dead: stream empty; B still lies (hidden pid)
            syscall_map = {}
            proc_map = dict(base_procs)
            pulses = [5]
        elif dead == "B":
            # B (/proc) dead: empty view; A still sees hidden pid, C fine
            syscall_map = {}
            for sample in SyscallSensor(base_events).stream():
                syscall_map[sample["pid"]] = sample["syscalls"]
            proc_map = {}
            pulses = [5]
        else:
            # C (heartbeat) dead: A sees pid, B edited, but pulse vanishes
            syscall_map = {}
            for sample in SyscallSensor(base_events).stream():
                syscall_map[sample["pid"]] = sample["syscalls"]
            proc_map = dict(base_procs)
            pulses = [0]
        v, ev = MultiChannelDetector().fuse_epoch(syscall_map, proc_map,
                                                  pulses)
        out.append("  Dead channel %s          | %s" %
                   (dead, "; ".join(v)))
        out.append("  %-25s |   evidence: %s" %
                   (" ", "; ".join(ev) or "-"))
    out.append("-" * 70)
    out.append("  The surviving channel is the one the attacker did NOT")
    out.append("  control; a fused detector keeps running on what remains.")
    out.append(L)
    return "\n".join(out)


# --------------------------------------------------------------------------
# Game / run loop
# --------------------------------------------------------------------------

def main(argv=None):
    print(run_matrix())
    print()
    print(channel_suppression_report())
    print()
    print(production_integration_note())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))